require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - script/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
